name: CIH
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildogh:
    runs-on: self-hosted
    steps:
     - uses: actions/checkout@v3
     - name: HRun a one-line script
       run: echo HHello, world!
     - name: Run a multi-line script
       run: |
         echo HAdd other actions to build,
         echo Htest, and deploy your project.
